const entry = (term, plain, why, example = '', technical = '') => ({ term, plain, why, example, technical });

export const GLOSSARY = Object.freeze([
  entry('Segmentation', 'Dividing a larger market, customer base, employee population, organization, or other population into meaningful groups whose needs, characteristics, behaviors, attitudes, or responses differ.', 'It helps avoid assuming one average describes everyone.', 'Group customers by evidenced differences in adoption willingness and trust.'),
  entry('Targeting', 'Selecting which segment or segments an organization will prioritize.', 'Limited resources require an explicit choice about whom to serve and why.', 'Prioritize a segment whose needs fit the organization’s capabilities.'),
  entry('Positioning', 'How an organization wants a target customer to understand an offering relative to alternatives.', 'A clear position connects a relevant benefit to credible evidence.', 'Present a service as the easiest verified option for a specific customer group.'),
  entry('Differentiation', 'How an offering is meaningfully different from alternatives in ways that matter to the target customer.', 'A difference creates value only when customers care about it and believe it.', 'Faster setup matters only if setup time is important to the target group.'),
  entry('Trust', 'A reasoned willingness to rely on someone or something under uncertainty.', 'Trust can influence adoption and verification, while excessive reliance can reduce scrutiny.'),
  entry('Agency', 'The meaningful ability to understand options, influence a decision, question it, change course, or decline.', 'People may comply without having meaningful choice.'),
  entry('Resistance', 'Delay, disagreement, refusal, modification, or protective pushback toward a change.', 'Resistance may reveal poor fit, risk, structural barriers, or useful criticism.'),
  entry('Readiness', 'The current pattern of conditions that may support or constrain a proposed action.', 'A readiness score is a discussion indicator, not proof that an initiative will succeed.'),
  entry('Maturity', 'How established, repeatable, supported, and evidence-informed a capability appears to be.', 'Maturity describes reported capability conditions; it does not rank people’s worth or potential.'),
  entry('Adoption', 'Trying, accepting, purchasing, implementing, using, or continuing a change, product, process, or technology.', 'Initial use, willing use, and sustained appropriate use are different outcomes.'),
  entry('Perceived Value', 'A person’s view of the relevant benefits compared with cost, effort, alternatives, and consequences.', 'Perceived value often influences consideration, but does not prove actual benefit.'),
  entry('Perceived Risk', 'A person’s interpretation of the likelihood and consequence of possible loss, harm, failure, or uncertainty.', 'Perceived risk can shape protective behavior and should be compared with documented hazards and experience.'),
  entry('Customer Lifetime Value', 'An estimate of the value generated by a customer relationship over a defined period and under stated assumptions.', 'It supports acquisition and retention decisions when revenue, margin, retention, and cost definitions are consistent.', '', 'CEAM+ distinguishes revenue CLV from margin or contribution CLV.'),
  entry('CAC', 'Customer acquisition cost: acquisition spending divided by the number of customers acquired under matching definitions and time periods.', 'It helps evaluate acquisition efficiency but does not measure customer quality by itself.'),
  entry('CLV:CAC', 'The ratio of customer lifetime value to customer acquisition cost using compatible value and cost definitions.', 'It is a scenario indicator whose meaning depends on the CLV model, attribution, cash timing, and segment mix.'),
  entry('ROMI', 'Return on marketing investment: incremental marketing contribution or profit relative to marketing investment.', 'It connects marketing spending with financial return when incrementality and cost assumptions are explicit.'),
  entry('ROAS', 'Return on advertising spend: attributed advertising revenue divided by advertising spend.', 'ROAS is narrower than profit or ROMI and can look strong while contribution is weak.'),
  entry('Conversion', 'Movement from one explicitly defined stage to another, such as visitor to purchaser.', 'Clear stage definitions and matching populations prevent misleading rates.'),
  entry('Retention', 'The share or count of a defined starting group that remains active at a later point.', 'Cohort definitions matter because new customers can distort aggregate retention.'),
  entry('Churn', 'The share or count of a defined starting group that leaves or becomes inactive during a period.', 'It helps identify loss patterns but does not explain why people left.'),
  entry('Market Share', 'A company’s sales, revenue, customers, or units as a share of a clearly defined market total.', 'The market, measure, geography, and period must match.'),
  entry('Break-even', 'The point where modeled revenue or contribution covers the included fixed costs.', 'It makes volume and cost assumptions visible; it does not guarantee demand.'),
  entry('Contribution Margin', 'Revenue remaining after the variable costs included in the calculation.', 'It shows what is available to cover fixed costs and profit under stated cost definitions.'),
  entry('SWOT', 'A structured review of strengths, weaknesses, opportunities, and threats.', 'It organizes evidence but should not become an unsupported list of opinions.'),
  entry("Porter's Five Forces", 'A framework for examining rivalry, buyers, suppliers, substitutes, and potential entrants.', 'It helps investigate sources of competitive pressure without reducing them to one universal score.'),
  entry('PESTEL', 'A scan of political, economic, social, technological, environmental, and legal conditions.', 'It keeps external conditions and plausible changes visible.'),
  entry('Ansoff', 'A framework comparing growth through existing or new products and existing or new markets.', 'It surfaces different capability, evidence, and risk requirements for each growth path.'),
  entry('RFM', 'Recency, frequency, and monetary value observations for customer activity.', 'It can describe behavioral groups when transaction definitions and time windows are appropriate; it does not reveal motives.'),
  entry('Cognitive', 'What people know, understand, believe, perceive, interpret, expect, or think they know.', 'Cognitive indicators help explain how information and mental models shape decisions.'),
  entry('Ethical', 'Fairness, transparency, responsibility, privacy, consent, trust, agency, accountability, and oversight.', 'Ethical conditions can change whether an otherwise feasible action is acceptable.'),
  entry('Model', 'Whether the underlying business, organizational, technological, financial, analytical, or operational system can work.', 'Positive attitudes cannot compensate for an infeasible system.'),
  entry('Plus', 'A specifically explained contextual factor such as regulation, culture, market conditions, dependencies, structural barriers, anomalies, or emerging change.', 'Plus keeps material context visible without becoming a miscellaneous category.'),
  entry('Cross-Dimension Variable', 'A variable that relates meaningfully to more than one CEAM+ dimension or assessment area.', 'It can reveal a recurring concern without implying that it caused an outcome.', 'Trust may appear in Ethical, Cognitive, Adoption, and Model evidence.'),
  entry('Decision-Sensitive Variable', 'A variable for which a relatively small change could materially alter interpretation, feasibility, recommendation, or outcome.', 'It prevents a favorable average from hiding a critical weakness.'),
  entry('Evidence Confidence', 'How strongly the available evidence supports an interpretation.', 'CEAM+ evidence support is user-declared and separate from statistical confidence.'),
  entry('Uncertainty', 'What remains unknown, missing, contradictory, unstable, or open to alternative explanations.', 'High uncertainty limits the strength of a conclusion without automatically counting as a negative score.'),
  entry('Sensitivity Analysis', 'A structured check of how a result changes when one or more supported assumptions or inputs change.', 'It identifies which variables can change a decision. A scenario is not a prediction.'),
]);

const escape = value => String(value ?? '').replace(/[&<>"']/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[char]);
const slug = term => term.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');

export function glossaryTerm(term, label = term) {
  const found = GLOSSARY.find(item => item.term.toLowerCase() === term.toLowerCase());
  return found ? `<button type="button" class="ceam-term" data-ceam-term="${escape(found.term)}" aria-label="Define ${escape(found.term)}">${escape(label)}</button>` : escape(label);
}

export function glossaryHTML() {
  return `<section class="ceam-glossary" aria-labelledby="ceam-glossary-title"><div class="section-heading"><span class="eyebrow">Plain-language definitions</span><h2 id="ceam-glossary-title">CEAM+ Glossary</h2><p>Search or open a term. Each definition explains what it means and why it matters.</p></div><label class="ceam-glossary-search">Search definitions<input type="search" data-glossary-search autocomplete="off" placeholder="Try trust, segmentation, or sensitivity"></label><p class="ceam-glossary-status" data-glossary-status role="status" aria-live="polite"></p><div class="ceam-glossary-list">${GLOSSARY.map(item => `<details id="glossary-${slug(item.term)}" data-glossary-entry data-term="${escape(item.term.toLowerCase())}"><summary>${escape(item.term)}</summary><p>${escape(item.plain)}</p><p><strong>Why it matters:</strong> ${escape(item.why)}</p>${item.example ? `<p><strong>Example:</strong> ${escape(item.example)}</p>` : ''}${item.technical ? `<p><strong>Technical note:</strong> ${escape(item.technical)}</p>` : ''}</details>`).join('')}</div></section>`;
}

export function initGlossary(root = document) {
  root.querySelectorAll('[data-ceam-glossary]').forEach(container => { if (!container.dataset.ready) { container.innerHTML = glossaryHTML(); container.dataset.ready = 'true'; } });
  root.querySelectorAll('[data-glossary-search]').forEach(input => input.addEventListener('input', () => {
    const query = input.value.trim().toLowerCase();
    const entries = [...input.closest('.ceam-glossary').querySelectorAll('[data-glossary-entry]')];
    let shown = 0;
    entries.forEach(item => { item.hidden = Boolean(query) && !item.textContent.toLowerCase().includes(query); if (!item.hidden) shown++; });
    input.closest('.ceam-glossary').querySelector('[data-glossary-status]').textContent = query ? `${shown} definition${shown === 1 ? '' : 's'} found.` : '';
  }));
  if (!document.documentElement.dataset.ceamGlossaryEvents) {
    document.documentElement.dataset.ceamGlossaryEvents = 'true';
    document.addEventListener('click', event => {
      const button = event.target.closest?.('[data-ceam-term]'); if (!button) return;
      const target = document.getElementById(`glossary-${slug(button.dataset.ceamTerm)}`); if (!target) return;
      for (let node = target.parentElement; node; node = node.parentElement) if (node.tagName === 'DETAILS') node.open = true;
      target.hidden = false; target.open = true; target.scrollIntoView({ behavior: 'smooth', block: 'center' }); target.querySelector('summary')?.focus();
    });
  }
}
