import { surveys, surveyCategories, surveyScale, summarizeSurvey } from './definitions.mjs';
import { loadState, saveDraft, saveResult, getHistory, deleteDraft, assessmentKey, clearAssessment } from '../assessments/storage.mjs';

const root = document.querySelector('#survey-catalogue');
const escape = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
// Reuse the persistence engine with a separate namespace: survey responses are not assessment results.
const storage = { getItem: () => localStorage.getItem('ceamplus.surveys.v1'), setItem: (_, value) => localStorage.setItem('ceamplus.surveys.v1', value) };
let active, response, result, saving = false, lastScope, filter = 'All';
const label = value => surveyScale.find(([id]) => id === value)?.[1] || 'Unanswered';
const heading = '<span class="eyebrow">Survey categories</span><h2>Choose the perspective you want to understand.</h2><p>13 short surveys in the same four categories as the Assessment Center. Each has five statements about a respondent’s experience, followed by optional notes.</p>';
const status = message => { root.querySelector('[data-survey-status]').textContent = message; };
function persist() {
  if (!saving) return;
  const saved = result ? saveResult(active, {...response, savingOptIn:true}, result, storage) : saveDraft(active, {...response, savingOptIn:true}, storage);
  if (saved.ok) {
    if (lastScope && assessmentKey(active, lastScope) !== assessmentKey(active, response)) deleteDraft(active, lastScope, storage);
    lastScope = structuredClone(response);
  }
  status(saved.ok ? 'Saved in this browser only.' : `Saving unavailable. You can still review and download this response. ${saved.error}`);
  return saved;
}
function focus() { const h = root.querySelector('h2'); h.tabIndex = -1; h.focus({preventScroll:true}); h.scrollIntoView({block:'start',behavior:'instant'}); }
function catalogue() {
  active = null;
  const loaded = loadState(storage);
  const records = Object.values(loaded.state.results).flat().filter(r => surveys.some(s => s.id === r.assessmentId));
  const drafts = Object.values(loaded.state.drafts).filter(r => surveys.some(s => s.id === r.assessmentId));
  const shown = surveys.filter(s => filter === 'All' || s.category === filter);
  root.innerHTML = heading + `<div class="survey-filters" role="group" aria-label="Survey categories">${['All',...surveyCategories].map(c=>`<button type="button" class="button secondary" data-survey-filter="${escape(c)}" aria-pressed="${c===filter}">${escape(c)}</button>`).join('')}</div><p>${shown.length} surveys · Existing context surveys are also available below.</p><div class="survey-card-grid">${shown.map(s=>`<article data-survey-card="${s.assessmentId}"><span class="eyebrow">${escape(s.category)}</span><h3>${escape(s.title)}</h3><p>${escape(s.audience)} · 3–5 minutes</p><p>Explore ${s.questions.map(q=>escape(q.construct.toLowerCase())).join(', ')}.</p><button type="button" class="button primary" data-survey-start="${s.id}">Start Survey</button> <a href="assessment-center.html?assessment=${s.assessmentId}">Related assessment</a></article>`).join('')}</div><details class="survey-saved"><summary>Saved surveys in this browser (${records.length} results, ${drafts.length} drafts)</summary><p>These responses stay separate from assessment scores. No new survey responses are uploaded.</p>${!loaded.ok?`<p>${escape(loaded.error)}</p>`:''}${drafts.map((r,i)=>`<p><button type="button" class="button secondary" data-survey-resume="${i}">Resume ${escape(surveys.find(s=>s.id===r.assessmentId).title)}</button></p>`).join('')}${records.map((r,i)=>`<p><button type="button" class="button secondary" data-survey-open="${i}">Open ${escape(surveys.find(s=>s.id===r.assessmentId).title)} — ${escape(new Date(r.createdAt).toLocaleString())}</button></p>`).join('')}<p>Remove only the saved survey you select:</p>${surveys.filter(s=>records.some(r=>r.assessmentId===s.id)||drafts.some(r=>r.assessmentId===s.id)).map(s=>`<button type="button" class="button secondary" data-survey-clear="${s.id}">Delete saved ${escape(s.title)}</button>`).join('')}</details><p data-survey-status role="status"></p>`;
  root.querySelectorAll('[data-survey-filter]').forEach(b=>b.onclick=()=>{filter=b.dataset.surveyFilter;catalogue();});
  root.querySelectorAll('[data-survey-start]').forEach(b=>b.onclick=()=>start(b.dataset.surveyStart));
  root.querySelectorAll('[data-survey-resume]').forEach(b=>b.onclick=()=>{const r=drafts[Number(b.dataset.surveyResume)];start(r.assessmentId,r.response);});
  root.querySelectorAll('[data-survey-open]').forEach(b=>b.onclick=()=>{const r=records[Number(b.dataset.surveyOpen)];active=surveys.find(s=>s.id===r.assessmentId);response=structuredClone(r.response);saving=true;result=summarizeSurvey(active,response.answers);report();focus();});
  root.querySelectorAll('[data-survey-clear]').forEach(b=>b.onclick=()=>{const survey=surveys.find(s=>s.id===b.dataset.surveyClear);if(!confirm(`Delete saved responses and drafts for ${survey.title} in this browser?`))return;const outcome=clearAssessment(survey,storage);catalogue();status(outcome.ok?'Selected survey records deleted.':outcome.error);});
}
function start(id, previous) {
  active=surveys.find(s=>s.id===id);response=previous?structuredClone(previous):{answers:{},context:'Individual respondent',initiative:'',role:'',notes:''};
  saving=!!previous?.savingOptIn;lastScope=previous?structuredClone(previous):null;result=null;edit();focus();
}
function saveControl() { return `<label class="survey-check"><input type="checkbox" id="survey-save"${saving?' checked':''}><span>Optional: save this survey in this browser. Checking this box does not submit it. Anyone using this browser profile may access saved responses.</span></label>`; }
function bindCommon() {
  root.querySelector('[data-survey-home]').onclick=()=>{persist();catalogue();focus();};
  root.querySelector('#survey-save').onchange=e=>{saving=e.target.checked;persist();if(!saving)status('Saving is off. Previously saved records remain in Saved surveys.');};
}
function edit() {
  root.innerHTML=`<button type="button" class="button secondary" data-survey-home>All Surveys</button><h2>${escape(active.title)}</h2><p>${escape(active.audience)}. Answer from your own experience of one initiative. For workplace statements, use your organization or team as the context.</p><p><strong>Response scale:</strong> 1 Strongly disagree · 2 Disagree · 3 Neither agree nor disagree · 4 Agree · 5 Strongly agree. Choose Not sure or Not applicable when needed.</p><p>${escape(active.validationStatus)}. ${escape(active.interpretation)}</p><form id="companion-survey-form"><div class="survey-context"><label>Initiative or topic (optional)<input name="initiative" value="${escape(response.initiative)}"></label><label>Your role or perspective (optional; no name needed)<input name="role" value="${escape(response.role)}"></label></div><p id="survey-progress" aria-live="polite"></p>${active.questions.map((q,i)=>`<fieldset class="survey-question"><legend>${i+1}. ${escape(q.text)}</legend>${surveyScale.map(([value,text])=>`<label><input type="radio" name="${q.id}" value="${value}"${response.answers[q.id]===value?' checked':''}><span>${value.length===1?value+' — ':''}${escape(text)}</span></label>`).join('')}</fieldset>`).join('')}<label>Optional example, uncertainty, or support you would find useful<textarea name="notes">${escape(response.notes)}</textarea></label><p>Do not enter sensitive personal information. These new category surveys stay in this tab unless you choose browser saving or download a copy. They do not use the older survey email submission service.</p>${saveControl()}<p data-survey-status role="status"></p><button type="submit" class="button primary">Review Survey Responses</button></form>`;
  bindCommon();const form=root.querySelector('form');const progress=()=>{root.querySelector('#survey-progress').textContent=`${summarizeSurvey(active,response.answers).answered} of ${active.questions.length} statements answered. You can change any response before reviewing.`;};progress();
  form.oninput=e=>{if(e.target.type==='radio')response.answers[e.target.name]=e.target.value;else if(['initiative','role','notes'].includes(e.target.name))response[e.target.name]=e.target.value;if(e.target.name==='role')response.tailoringSignature='survey-perspective-v1:'+response.role.trim().toLowerCase();progress();persist();};
  form.onsubmit=e=>{e.preventDefault();response.resultId ||= crypto.randomUUID();response.completedAt ||= new Date().toISOString();result=summarizeSurvey(active,response.answers);persist();report();focus();};
}
function report() {
  const history=getHistory(active,response,storage);
  const before=history.baseline?.response.answers;
  const list=questions=>questions.length?`<ul>${questions.map(q=>`<li>${escape(q.construct)}: “${escape(q.text)}” — ${escape(label(response.answers[q.id]))}</li>`).join('')}</ul>`:'<p>No responses in this group.</p>';
  root.innerHTML=`<button type="button" class="button secondary" data-survey-home>All Surveys</button><h2>${escape(active.title)} — Response Summary</h2><p><strong>Initiative:</strong> ${escape(response.initiative||'Not specified')} · <strong>Perspective:</strong> ${escape(response.role||'Not specified')}</p><p>${result.answered} of ${result.total} answered. This is one person’s self-report, not an organizational maturity score or a representative survey result.</p><div class="survey-card-grid"><article><h3>Reported positive experiences</h3>${list(result.reportedStrengths)}</article><article><h3>Areas to discuss</h3>${list(result.discussionNeeds)}<p>Ask what conditions explain each response, and what practical support would help. Disagreement is not proof of unwillingness or poor performance.</p></article></div><h3>All responses</h3><ol>${active.questions.map(q=>`<li><p>${escape(q.text)}<br><strong>${escape(label(response.answers[q.id]))}</strong></p></li>`).join('')}</ol><p>Not sure: ${result.uncertain.length} · Not applicable: ${result.notApplicable.length} · Unanswered: ${result.unanswered.length}. These are not counted as negative responses.</p><p><strong>Respondent’s notes:</strong> ${escape(response.notes||'No notes supplied.')}</p><h3>What to do next</h3><p>Review the reported experiences with the respondent’s consent. Request examples and compare them with other perspectives or records. Use the related assessment to examine organizational conditions; survey answers are not automatically copied into it.</p><a class="button primary" href="assessment-center.html?assessment=${active.assessmentId}">Open Related Assessment</a><h3>Follow-up</h3><p>After an agreed action, repeat in 4–6 weeks or after the next relevant work or customer cycle. Keep the same respondent, initiative and survey version when comparing responses. Changes do not establish the effect of an action.</p>${before&&history.followUp?`<h4>Saved baseline and latest follow-up</h4><ul>${active.questions.map(q=>`<li>${escape(q.construct)}: ${escape(label(before[q.id]))} → ${escape(label(history.followUp.response.answers[q.id]))}</li>`).join('')}</ul>`:'<p>Save a baseline and a later follow-up for the same initiative to compare responses here.</p>'}<div class="survey-actions"><button type="button" class="button secondary" id="survey-edit">Edit Responses</button><button type="button" class="button secondary" id="survey-download">Download Survey JSON</button><button type="button" class="button secondary" id="survey-followup">Start Survey Follow-Up</button></div>${saveControl()}<p data-survey-status role="status"></p>`;
  bindCommon();root.querySelector('#survey-save').onchange=e=>{saving=e.target.checked;const saved=persist();report();status(saving?(saved?.ok?'Saved in this browser only.':`Saving unavailable: ${saved?.error}. Download a copy instead.`):'Saving is off. Previously saved records remain available.');};
  root.querySelector('#survey-edit').onclick=()=>{result=null;edit();focus();};
  root.querySelector('#survey-followup').onclick=()=>{const next={answers:{},context:response.context,initiative:response.initiative,role:response.role,tailoringSignature:response.tailoringSignature,notes:'',savingOptIn:saving};start(active.id,next);};
  root.querySelector('#survey-download').onclick=()=>{const url=URL.createObjectURL(new Blob([JSON.stringify({survey:active,response,result},null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=`ceam-${active.id}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
}
if(root){catalogue();const id=new URLSearchParams(location.search).get('survey');if(surveys.some(s=>s.assessmentId===id))start('survey-'+id);}
